"""capstone defence score

Revision ID: 2a4345e0753c
Revises: 0a9c5d7e080c
Created: 2026-09-09 16:13:17.500187
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a4345e0753c'
down_revision: Union[str, None] = '0a9c5d7e080c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capstones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('defence_breakdown', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capstones', schema=None) as batch_op:
        batch_op.drop_column('defence_breakdown')
        batch_op.drop_column('defence_score')

    # ### end Alembic commands ###
