"""initial schema

Revision ID: 0a9c5d7e080c
Revises: 
Created: 2026-09-08 12:09:02.306191
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a9c5d7e080c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('evidence_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module_key', sa.String(length=64), nullable=False),
    sa.Column('cohort', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_key', 'cohort')
    )
    with op.batch_alter_table('module_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_flags_module_key'), ['module_key'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('assessment_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('recommended_topics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_results_user_id'), ['user_id'], unique=False)

    op.create_table('capstones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('approach', sa.Text(), nullable=False),
    sa.Column('run_ids', sa.JSON(), nullable=False),
    sa.Column('figures', sa.JSON(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('future_work', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capstones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capstones_user_id'), ['user_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('track', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('accession', sa.String(length=64), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_format', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_report', sa.JSON(), nullable=False),
    sa.Column('supported_modules', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_datasets_track'), ['track'], unique=False)

    op.create_table('design_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('brief_id', sa.String(length=64), nullable=False),
    sa.Column('biological_question', sa.Text(), nullable=False),
    sa.Column('condition_structure', sa.Text(), nullable=False),
    sa.Column('sample_structure', sa.Text(), nullable=False),
    sa.Column('decision_goal', sa.Text(), nullable=False),
    sa.Column('chosen_assay', sa.String(length=64), nullable=False),
    sa.Column('assay_justification', sa.Text(), nullable=False),
    sa.Column('samples', sa.JSON(), nullable=False),
    sa.Column('design_warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('design_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_design_plans_user_id'), ['user_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('program_code', sa.String(length=64), nullable=False),
    sa.Column('cohort', sa.String(length=64), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'program_code')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_user_id'), ['user_id'], unique=False)

    op.create_table('entitlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entitlements_user_id'), ['user_id'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('term_days', sa.Integer(), nullable=False),
    sa.Column('amount_minor_units', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('entitlement_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_user_id'), ['user_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('track', sa.String(length=16), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('program_code', sa.String(length=64), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('access_tier', sa.String(length=16), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('method_versions', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parent_run_id', sa.String(length=36), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('last_valid_step', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['parent_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_user_id'), ['user_id'], unique=False)

    op.create_table('ai_interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('function', sa.String(length=32), nullable=False),
    sa.Column('step', sa.String(length=64), nullable=False),
    sa.Column('prompt_context', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('evidence_source_ids', sa.JSON(), nullable=False),
    sa.Column('computed_refs', sa.JSON(), nullable=False),
    sa.Column('interpretation_label', sa.String(length=24), nullable=True),
    sa.Column('label_rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_interactions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_interactions_user_id'), ['user_id'], unique=False)

    op.create_table('interpretations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.String(length=64), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('statistical_evidence', sa.Text(), nullable=False),
    sa.Column('biological_interpretation', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interpretations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interpretations_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interpretations_user_id'), ['user_id'], unique=False)

    op.create_table('perturbations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('parameter_key', sa.String(length=64), nullable=False),
    sa.Column('from_value', sa.JSON(), nullable=False),
    sa.Column('to_value', sa.JSON(), nullable=False),
    sa.Column('scientific_reason', sa.Text(), nullable=False),
    sa.Column('evidence_source_ids', sa.JSON(), nullable=False),
    sa.Column('expected_consequence', sa.JSON(), nullable=False),
    sa.Column('what_to_observe', sa.Text(), nullable=False),
    sa.Column('limitation', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('alternate_run_id', sa.String(length=36), nullable=True),
    sa.Column('actual_outcome', sa.JSON(), nullable=False),
    sa.Column('divergence_explanation', sa.Text(), nullable=False),
    sa.Column('matched_expectation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alternate_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('perturbations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_perturbations_run_id'), ['run_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('generated_tier', sa.String(length=16), nullable=False),
    sa.Column('export_format', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('audit_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('interaction_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('learner_rationale', sa.Text(), nullable=False),
    sa.Column('final_interpretation', sa.Text(), nullable=False),
    sa.Column('revised_label', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['ai_interactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_records_interaction_id'), ['interaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_records_interaction_id'))

    op.drop_table('audit_records')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_run_id'))

    op.drop_table('reports')
    with op.batch_alter_table('perturbations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perturbations_run_id'))

    op.drop_table('perturbations')
    with op.batch_alter_table('interpretations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interpretations_user_id'))
        batch_op.drop_index(batch_op.f('ix_interpretations_run_id'))

    op.drop_table('interpretations')
    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_interactions_run_id'))

    op.drop_table('ai_interactions')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_dataset_id'))

    op.drop_table('runs')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_user_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entitlements_user_id'))

    op.drop_table('entitlements')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_user_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('design_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_design_plans_user_id'))

    op.drop_table('design_plans')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_track'))
        batch_op.drop_index(batch_op.f('ix_datasets_slug'))

    op.drop_table('datasets')
    with op.batch_alter_table('capstones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capstones_user_id'))

    op.drop_table('capstones')
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_results_user_id'))

    op.drop_table('assessment_results')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('module_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_flags_module_key'))

    op.drop_table('module_flags')
    op.drop_table('evidence_sources')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
