"""issue reports and run report link

Revision ID: fc6dd0e7071f
Revises: 2a4345e0753c
Created: 2026-09-11 10:37:59.504548
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc6dd0e7071f'
down_revision: Union[str, None] = '2a4345e0753c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('screen', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_reports_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_reports_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_runs_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_report_id'))
        batch_op.drop_column('report_id')

    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_issue_reports_status'))
        batch_op.drop_index(batch_op.f('ix_issue_reports_run_id'))

    op.drop_table('issue_reports')
    # ### end Alembic commands ###
